development:
  adapter: postgresql
  encoding: unicode
  database: demo_app9_development
  pool: 5
  username: demo_app9
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: demo_app9_test
  pool: 5
  username: demo_app9
  password: password1

production:
  adapter: postgresql
  encoding: unicode
  database: demo_app9_production
  pool: 5
  username: myapp
  password: password1